version: "3.3"
services:
  api:
    container_name: "api"
    build: "."
    ports:
      - "80:5000"
    volumes:
      - api-data:/go/src/app
    restart: "always"
    env_file:
      - ".env"
volumes:
  api-data:
