version: '3.3'
services:
    api:
        container_name: 'api'
        build: '.'
        ports: 
            - '5000:5000'
        volumes: 
            - api-data:/go/src/app
        depends_on: 
            - 'mongodb'
        restart: 'always'
        networks:
            - thatmemenet 
        env_file: 
            - '.env'
        environment: 
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
            - MONGODB_DATABASE=thatmemedev
            - ELASTICSEARCH_URL=http://elasticsearch:9200/
    mongodb:
        image: 'mongo:latest'
        container_name: 'mongodb'
        ports: 
            - '27017:27017'
        depends_on: 
            - 'elasticsearch'
        volumes: 
            - mongodb-data:/data
        networks:
            - thatmemenet 
    elasticsearch:
        image: 'elastic/elasticsearch:7.6.2'
        container_name: 'elasticsearch'
        ports:
            - '9200:9200'
        environment: 
            - discovery.type=single-node
        volumes: 
            - es-data:/usr/share/elasticsearch/data
        networks:
            - thatmemenet 

volumes: 
    api-data:
    mongodb-data:
    es-data:
networks: 
    thatmemenet:
        driver: bridge        
        